apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux-webpage
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: project-webpage:v1
        image: nginx
        ports:
        - containerPort: 8080
